inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
  DisplayCopNames: true

Layout/LineLength:
  Max: 154

Lint/UselessAssignment:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Enabled: true
  Max: 20

Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/*

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*"


Style/Documentation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/home_controller.rb'

Style/GuardClause:
  MinBodyLength: 5

Style/ExpandPathArguments:
    Exclude:
      - 'config/unicorn.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/deploy.rb'
    - 'config/deploy/production.rb'

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false