version: '3'
services:
  db:
    image: mysql:5.6.47
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "4306:3306"
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec puma -C config/puma.rb
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/bundle
    volumes:
      - .:/saunars-circle
      - ~/.ssh:/root/.ssh
      - bundle_path:/bundle
      - sockets:/saunars-circle/tmp/sockets
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - web
    volumes:
      - ./nginx/log:/var/log/nginx
      - public_data:/saunars-circle/public
      - tmp_data:/saunars-circle/tmp
      - sockets:/saunars-circle/tmp/sockets
volumes:
  bundle_path:
  mysql_data:
  public_data:
  tmp_data:
  sockets: