version: '3'
services:
  db:
    image: mysql:5.6.47
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "4306:3306"
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/bundle
    volumes:
      - .:/app_name
      - ~/.ssh:/root/.ssh
      - bundle_path:/bundle
volumes:
  bundle_path:
  mysql_data: