version: 2.1
jobs:
  build:
    docker:
        - image: circleci/ruby:2.5.1-node-browsers
          environment:
            - RAILS_ENV: test
            - RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
        - image: circleci/mysql:5.6.47
          environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            - MYSQL_HOST: '%'

    working_directory: ~/repo

    steps:
      - checkout # CI環境上の working_directory の値の場所にGitリポジトリをコピーする
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      
      - run: gem install bundler -v 1.16.6
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      
      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      
      - run: bundle exec rubocop
      
      - run: bundle exec rspec
      
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      
      - add_ssh_keys:
          fingerprints:
            - "25:e3:e5:19:0d:09:52:e8:89:b5:1e:f9:fd:2b:92:75"
      
      - deploy:
          name: Capistrano deploy
          command:
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              exit 0
            fi
            bundle exec cap production deploy
